model: TSFormer
data: voc2007
seed: 0
lr: 1e-05
batch_size: 16
mode: part
optimizer: AdamW
lr_scheduler: ReduceLROnPlateau
weight_decay: 0.0001
start_depth: 4
img_size: 448
num_heads: 1
embed_type: bert
loss_fn: bce
gamma_pos: 0.0
gamma_neg: 1.0
clip: 0.05
max_epoch: 100
warmup_epoch: 2
topk: 3
threshold: 0.5
pretrained: True
restore_exp: None
train_path: data/voc2007/train.txt
test_path: data/voc2007/test.txt
label_path: data/voc2007/label.txt
embed_path: data/voc2007/bert.npy
ignore_path: data/voc2007/ignore.npy
num_classes: 20
exp_dir: experiments/TSFormer_voc2007/exp1
log_path: experiments/TSFormer_voc2007/exp1/train.log
ckpt_dir: experiments/TSFormer_voc2007/exp1/checkpoints
ckpt_best_path: experiments/TSFormer_voc2007/exp1/checkpoints/best_model.pth
ckpt_latest_path: experiments/TSFormer_voc2007/exp1/checkpoints/latest_model.pth
